

---
version: "2.0"

services:
  nfa-proxy:
    image: docker.io/srt0422/openai-morpheus-proxy:v0.0.31
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - INTERNAL_API_PORT=8080
      - MARKETPLACE_PORT=3333
      - MARKETPLACE_BASE_URL=localhost:8080
      - MARKETPLACE_URL=localhost:8080
      - SESSION_DURATION=1h
      - PROXY_URL=/v1
      - CONSUMER_NODE_URL=localhost:8080

  consumer-node:
    image: docker.io/srt0422/morpheus-marketplace:v0.0.16
    expose:
      - port: 8082
        as: 80
        to:
          - global: true
    env:
      - PROXY_ADDRESS=0.0.0.0:3333
      - WEB_ADDRESS=0.0.0.0:8082
      - WALLET_PRIVATE_KEY=0x0d4205f04cb068af53ba92b5be90d99ee52b477bdfc72812a752dbb43fdae30b
      - DIAMOND_CONTRACT_ADDRESS=0xb8C55cD613af947E73E262F0d3C54b7211Af16CF
      - MOR_TOKEN_ADDRESS=0x34a285a1b1c166420df5b6630132542923b5b27e
      - EXPLORER_API_URL=https://api-sepolia.arbiscan.io/api
      - ETH_NODE_CHAIN_ID=421614
      - ENVIRONMENT=development
      - ETH_NODE_USE_SUBSCRIPTIONS=false
      - ETH_NODE_ADDRESS=wss://arbitrum-sepolia.infura.io/ws/v3/1adb802601424030ab61832103b6c102
      - ETH_NODE_LEGACY_TX=false
      - PROXY_STORE_CHAT_CONTEXT=true
      - PROXY_STORAGE_PATH=./data/
      - LOG_COLOR=true
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - PROVIDER_CACHE_TTL=60
      - MAX_CONCURRENT_SESSIONS=100
      - SESSION_TIMEOUT=3600

profiles:
  compute:
    nfa-proxy:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    consumer-node:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi

  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        nfa-proxy:
          denom: uakt
          amount: 1000
        consumer-node:
          denom: uakt
          amount: 1000

deployment:
  nfa-proxy:
    dcloud:
      profile: nfa-proxy
      count: 1
  consumer-node:
    dcloud:
      profile: consumer-node
      count: 1
